server:
 port: 8080
mybatis:
 mapper-locations: # 所有的mapper映射文件
   - classpath:mapping/*.xml
spring:
 application:
    name: cloud-provider
 datasource:
   type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
   driver-class-name: com.mysql.cj.jdbc.Driver # 配置MySQL的驱动程序类
   url: jdbc:mysql://localhost:3307/springcloud?serverTimezone=GMT%2B8 # 数据库连接地址
   username: root # 数据库用户名
   password: root # 数据库连接密码
# security:
#    user:
#      name: admin  # 认证用户名
#      password: wj  # 认证密码
#      roles:
#       - USER # 授权角色
#logging:
#  level:
#    cn.enjoy.mapper: debug
#
#
##指定Eureka的配置
eureka:
  #客服端配置
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka
      #配置用户名和密码的格式
      #defaultZone: http://admin:wj@localhost:7001/eureka  #这样设置连接 在springcloud2中必须设置EurekaSecurityConfig类
      #注册到多个地址，可以只写一个地址，这个eureka会将注册信息复制到集群中的其它eureka中，但是不建议这样做，如果这台eureka挂了，会有影响
      defaultZone: http://admin:wj@eureka:7001/eureka,http://admin:wj@eureka2:7002/eureka,http://admin:wj@eureka3:7003/eureka
  instance:
    instance-id: cloud-provider
    prefer-ip-address: true
    #设置心跳
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
info:
  app.name: cloud-provider
  company.name: wj
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

#eureka:
#  client: # 客户端进行Eureka注册的配置
#    register-with-eureka: true
#    service-url:
#      #defaultZone: http://localhost:7001/eureka
#      defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
#  instance:
#    instance-id: microcloud-provider-product
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
#    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）
#
#info:
#  app.name: microcloud-provider-product
#  company.name: enjoy
#  build.artifactId: $project.artifactId$
#  build.modelVersion: $project.modelVersion$


